name: jenkins_api_client_func_tests
git: git://github.com/kbinani/jenkins_api_client.git
ref: master
script:
 - bundle install
 - rake unit_tests
 - rake func_tests
 notification_email: kbinani.bt@gmail.com
 notification_email_for_every_unstable: true
